id: 98
name: 50' Reefer
props:
    cargo_age_period: 185
    cargo_allow_refit:
    - 5
    - 12
    - 13
    - 35
    cargo_capacity: 30
    cargo_disallow_refit:
    - 1
    - 8
    - 14
    - 34
    - 44
    - 41
    - 25
    - 4
    cb_flags: 72
    climates_available: 15
    cost_factor: 81
    default_cargo_type: 12
    introduction_date:
    - 1935
    - 1
    - 1
    length: 7
    loading_speed: 8
    max_speed: 136
    misc_flags: 18
    model_life: 255
    non_refittable_cargo_classes: 1
    refittable_cargo_classes: 36
    reliability_decay: 20
    retire_early: 10
    running_cost_base: 19510
    running_cost_factor: 90
    sort_purchase_list: 128
    sprite_id: 253
    vehicle_life: 30
    visual_effect_and_powered: 64
    weight_low: 21
