id: 84
name: Superliner Car
props:
    cargo_age_period: 185
    cargo_allow_refit: []
    cargo_capacity: 50
    cargo_disallow_refit: []
    cb_flags: 8
    climates_available: 15
    cost_factor: 114
    introduction_date:
    - 1979
    - 1
    - 1
    loading_speed: 10
    max_speed: 160
    misc_flags: 18
    model_life: 255
    refittable_cargo_classes: 1
    reliability_decay: 20
    retire_early: 10
    running_cost_base: 19510
    running_cost_factor: 200
    sort_purchase_list: 128
    sprite_id: 253
    vehicle_life: 30
    visual_effect_and_powered: 64
    weight_low: 32
